server:
  port: 8000

feign:
  ratingService:
    url: "http://localhost:7777"
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true
    streamEnabled: true

spring:
  application:
    name: stores-dashboard

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    com:
      baeldung:
        cloud:
          openfeign:
            client: DEBUG